name: lint

on: [push]

jobs:
  build:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm i -g pnpm
      - run: pnpm i

      - name: Lint
        run: pnpm lint
