name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Setup cache
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ${{ runner.temp }}
          key: ${{ runner.os }}-${{ matrix.node }}-pnpm-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-pnpm-v2-
      - name: Install dependencies
        run: |
          npm i -g pnpm @antfu/ni
          pnpm config set store-dir ${{ runner.temp }}
          nci
      - name: Run test
        run: nr test --if-present
      - name: Run build
        run: nr build